-- Create bookmarks table
create table public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.bookmarks enable row level security;

-- Create policies
create policy "Users can view their own bookmarks"
  on public.bookmarks for select
  using ( (select auth.uid()) = user_id );

create policy "Users can insert their own bookmarks"
  on public.bookmarks for insert
  with check ( (select auth.uid()) = user_id );

create policy "Users can delete their own bookmarks"
  on public.bookmarks for delete
  using ( (select auth.uid()) = user_id );

-- Enable Realtime
alter publication supabase_realtime add table public.bookmarks;
